# Configuración explícita para evitar fallos de compilación en GitHub Pages
theme: null
plugins: []
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

include:
  - _astro
  - assets
  - .nojekyll

exclude:
  - src
  - public
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.mjs
  - astro.config.mjs
  - .astro
  - .github
